### ISSUE TITLE
Error: Bad Request     at fetch.then.response

### ISSUE THREAD

**Issue by franktopel** [gabiseabra/fontello-webpack-plugin#11]
Trying to use your plugin for the first time I'm having a hard time figuring it out.

As of now, this is my config:

```
{ 
  config: 'src/fonts/fontello/config.json',
  fonts: [ 'eot', 'woff', 'woff2', 'ttf', 'svg' ],
  output: { 
    css: 'src/fonts/fontello/fontello.scss',
    font: 'build/fonts/fontello/fontello' 
  } 
}
```

Using that config I am getting

```
Error: Bad Request
    at fetch.then.response (/Users/connexo/Sites/guso/node_modules/fontello-webpack-plugin/src/Fontello.js:47:12)
    at process._tickCallback (internal/process/next_tick.js:109:7)
Error: Not Found
    at session.then.then.response (/Users/connexo/Sites/guso/node_modules/fontello-webpack-plugin/src/Fontello.js:71:12)
    at process._tickCallback (internal/process/next_tick.js:109:7)
/Users/connexo/Sites/guso/node_modules/fontello-webpack-plugin/src/Css.js:135
			glyphs.map(({ code, css }) =>
			      ^

TypeError: Cannot read property 'map' of undefined
    at Css.get cssText [as cssText] (/Users/connexo/Sites/guso/node_modules/fontello-webpack-plugin/src/Css.js:135:10)
    at Css.source (/Users/connexo/Sites/guso/node_modules/fontello-webpack-plugin/src/Css.js:151:14)
    at /Users/connexo/Sites/guso/node_modules/webpack/lib/SourceMapDevToolPlugin.js:71:23
    at Array.map (native)
    at /Users/connexo/Sites/guso/node_modules/webpack/lib/SourceMapDevToolPlugin.js:53:85
    at Array.forEach (native)
    at Compilation.<anonymous> (/Users/connexo/Sites/guso/node_modules/webpack/lib/SourceMapDevToolPlugin.js:52:12)
    at Compilation.applyPlugins1 (/Users/connexo/Sites/guso/node_modules/tapable/lib/Tapable.js:75:14)
    at self.applyPluginsAsync.err (/Users/connexo/Sites/guso/node_modules/webpack/lib/Compilation.js:639:11)
    at next (/Users/connexo/Sites/guso/node_modules/tapable/lib/Tapable.js:202:11)
    at Compilation.compilation.plugin (/Users/connexo/Sites/guso/node_modules/webpack/lib/optimize/UglifyJsPlugin.js:230:5)
    at Compilation.applyPluginsAsyncSeries (/Users/connexo/Sites/guso/node_modules/tapable/lib/Tapable.js:206:13)
    at self.applyPluginsAsync.err (/Users/connexo/Sites/guso/node_modules/webpack/lib/Compilation.js:635:10)
    at next (/Users/connexo/Sites/guso/node_modules/tapable/lib/Tapable.js:202:11)
    at Compilation.compilation.plugin.cb (/Users/connexo/Sites/guso/node_modules/fontello-webpack-plugin/src/index.js:59:5)
    at Compilation.applyPluginsAsyncSeries (/Users/connexo/Sites/guso/node_modules/tapable/lib/Tapable.js:206:13)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webapp-starter@0.1.1 build: `gulp build --production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webapp-starter@0.1.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/connexo/.npm/_logs/2018-02-13T10_49_31_040Z-debug.log
```
This is my `config.json` from fontello.com:

```
{
  "name": "",
  "css_prefix_text": "icon-",
  "css_use_suffix": false,
  "hinting": true,
  "units_per_em": 1000,
  "ascent": 850,
  "glyphs": [
    {
      "uid": "e4dde1992f787163e2e2b534b8c8067d",
      "css": "angle-down",
      "code": 61703,
      "src": "fontawesome"
    },
    {
      "uid": "5de9370846a26947e03f63142a3f1c07",
      "css": "angle-up",
      "code": 61702,
      "src": "fontawesome"
    },
    {
      "uid": "7bf14281af5633a597f85b061ef1cfb9",
      "css": "angle-right",
      "code": 61701,
      "src": "fontawesome"
    },
    {
      "uid": "f3f90c8c89795da30f7444634476ea4f",
      "css": "angle-left",
      "code": 61700,
      "src": "fontawesome"
    },
    {
      "uid": "9f7e588c66cfd6891f6f507cf6f6596b",
      "css": "phone",
      "code": 59392,
      "src": "fontawesome"
    },
    {
      "uid": "0d6ab6194c0eddda2b8c9cedf2ab248e",
      "css": "attach",
      "code": 59393,
      "src": "fontawesome"
    },
    {
      "uid": "5bb103cd29de77e0e06a52638527b575",
      "css": "wrench",
      "code": 59394,
      "src": "fontawesome"
    },
    {
      "uid": "ccddff8e8670dcd130e3cb55fdfc2fd0",
      "css": "down-open",
      "code": 59395,
      "src": "fontawesome"
    },
    {
      "uid": "d870630ff8f81e6de3958ecaeac532f2",
      "css": "left-open",
      "code": 59396,
      "src": "fontawesome"
    },
    {
      "uid": "399ef63b1e23ab1b761dfbb5591fa4da",
      "css": "right-open",
      "code": 59397,
      "src": "fontawesome"
    },
    {
      "uid": "fe6697b391355dec12f3d86d6d490397",
      "css": "up-open",
      "code": 59398,
      "src": "fontawesome"
    },
    {
      "uid": "f4445feb55521283572ee88bc304f928",
      "css": "floppy",
      "code": 59399,
      "src": "fontawesome"
    },
    {
      "uid": "bf882b30900da12fca090d9796bc3030",
      "css": "mail",
      "code": 59400,
      "src": "fontawesome"
    },
    {
      "uid": "6274e0601f2feef7eced89146e708de0",
      "css": "user-add",
      "code": 59401,
      "src": "entypo"
    },
    {
      "uid": "ecf8edb95c3f45eb433b4cce7ba9f740",
      "css": "users",
      "code": 59402,
      "src": "entypo"
    },
    {
      "uid": "bbd66ef66bb8fa9edde54d9a90b89150",
      "css": "user",
      "code": 59403,
      "src": "entypo"
    }
  ]
}
```
Any ideas what I'm doing wrong?

**Comment by franktopel** [comment]
I was passing a path instead of a config object.
